# Generated by Django 4.0.6 on 2023-01-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное имя')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('company_name', models.CharField(max_length=512, verbose_name='Название компании')),
                ('document', models.FileField(upload_to='', verbose_name='Документ')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявка на сотрудничество',
                'verbose_name_plural': 'Заявки на сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='LogisticBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное имя')),
                ('departure_address', models.CharField(max_length=512, verbose_name='Адрес отправления')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Контактный телефон')),
                ('cargo_weight', models.PositiveIntegerField(verbose_name='Вес груза в КГ')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('cargo_descriptions', models.TextField(verbose_name='Описание груза')),
            ],
            options={
                'verbose_name': 'Логистическая заявка',
                'verbose_name_plural': 'Логистические заявки',
            },
        ),
    ]
