# Generated by Django 4.0.6 on 2023-01-25 08:26

from django.db import migrations, models
import moloko_backend.bids.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('company_name', models.CharField(max_length=512, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Заявка на прайс-лист',
                'verbose_name_plural': 'Заявки на прайс-листы',
            },
            bases=(moloko_backend.bids.mixins.SendEmailMixin, models.Model),
        ),
    ]
