# Generated by Django 4.0.6 on 2023-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_pricelistbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationbid',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cooperationbid',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='cooperationbid',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ'),
        ),
    ]
