[tool.black]
line-length = 80
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | env
  | venv
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = ["*/*/migrations"]