apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
configMapGenerator:
- files:
  - configs/environ
  name: app-config
  behavior: replace
patchesStrategicMerge:
  - patches/ingress.yaml
