# Generated by Django 4.0.6 on 2023-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermOfCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cooperation', 'Cooperation'), ('delivery', 'Delivery'), ('payment', 'Payment')], max_length=16, verbose_name='Тип условия')),
                ('term', models.CharField(max_length=512, verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Условие сотрудничества',
                'verbose_name_plural': 'Условия сотрудничества',
            },
        ),
    ]
