apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- depl/migrations.yaml
- depl/api.yaml
- depl/static.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- files:
  - configs/config.yaml
  name: app-config
