apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: api
          image: api_image
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config
              mountPath: /etc/moloko_backend
              readOnly: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENV_PATH
              value: /etc/moloko_backend/environ
            - name: SCHEMA
              value: https
            - name: DOMAIN
              value: ${DOMAIN}
          resources:
            requests:
              memory: 30Mi
