apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: migrations
spec:
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: migrations
    spec:
      restartPolicy: Never
      volumes:
        - name: app-config
          configMap:
            name: app-config
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: api
          image: api_image
          imagePullPolicy: Always
          command:
            - python
            - manage.py
            - migrate
          volumeMounts:
            - name: app-config
              mountPath: /etc/moloko_backend
              readOnly: true
          env:
            - name: ENV_PATH
              value: /etc/moloko_backend/environ
            - name: SCHEMA
              value: https
            - name: DOMAIN
              value: ${DOMAIN}
          resources:
            requests:
              memory: 10Mi
