apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app.kubernetes.io/name: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: static
  template:
    metadata:
      labels:
        app.kubernetes.io/name: static
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: static
          image: static_image
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config
              mountPath: /etc/moloko_backend
              readOnly: true
          env:
            - name: ENV_PATH
              value: /etc/moloko_backend/environ
            - name: SCHEMA
              value: https
            - name: DOMAIN
              value: ${DOMAIN}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 10Mi
