# Generated by Django 4.0.6 on 2023-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_alter_user_id_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=512, verbose_name='Отчество')),
                ('role', models.CharField(max_length=512, verbose_name='Должность')),
                ('portrait', models.FileField(upload_to='', verbose_name='Портрет')),
            ],
            options={
                'verbose_name': 'Управляющий',
                'verbose_name_plural': 'Управляющие',
            },
        ),
    ]
